# Default values for xdpdropper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: renanqts/xdpdropper
  pullPolicy: IfNotPresent

podAnnotations: {}

podSecurityContext: {}

env:
  - name: XDPDROPPER_IFACE
    value: enp1s0
  - name: XDPDROPPER_LOGLEVEL
    value: info

securityContext:
  # CAP_BPF seems to be not enough
  # TODO: Investigate why not
  # capabilities:
  #   add:
  #   - CAP_BPF
  privileged: true

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
